# Generated by Django 3.2.3 on 2021-05-27 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('area', models.IntegerField(verbose_name='Площадь')),
                ('quantity_of_rooms', models.IntegerField(verbose_name='Количество комнат')),
                ('phone', models.CharField(max_length=25, verbose_name='Номер телефона')),
                ('users_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
