# Generated by Django 3.2.3 on 2021-05-27 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.RemoveField(
            model_name='house',
            name='title',
        ),
    ]
