# Generated by Django 3.2.3 on 2021-05-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210527_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(choices=[('БИШКЕК', 'Бишкек'), ('ОШ', 'Ош'), ('БАТКЕН', 'Баткен'), ('ДЖАЛАЛ-АБАД', 'Джалал-Абад'), ('НАРЫН', 'Нарын'), ('ТАЛАС', 'Талас'), ('ЫСЫК-КОЛ', 'Ысык-Кол')], max_length=11, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='house',
            name='quantity_of_rooms',
            field=models.CharField(choices=[('1-КОМН.КВ', '1-Комн.Кв'), ('2-КОМН.КВ', '2-Комн.Кв'), ('3-КОМН.КВ', '3-Комн.Кв'), ('4-КОМН.КВ', '4-Комн.Кв')], max_length=9, verbose_name='Количество комнат'),
        ),
    ]
