# Generated by Django 3.2.3 on 2021-05-28 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='house_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hous_id', to='app.house'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(verbose_name='Лайк')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_id', to='app.house')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
    ]
